sudo: required
services: 
  - docker

before_install: 
  - docker build -t saikaushik/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run saikaushik/react-test npm test -- --coverage

after_success: 
  - docker build -t saikaushik/multi-client ./client
  - docker build -t saikaushik/multi-nginx ./nginx
  - docker build -t saikaushik/multi-server ./server
  - docker build -t saikaushik/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push to docker hub
  - docker push saikaushik/multi-client
  - docker push saikaushik/multi-nginx
  - docker push saikaushik/multi-server
  - docker push saikaushik/multi-worker
